site_name: "violetear"
site_url: https://apiad.net/violetear
repo_url: https://github.com/apiad/violetear

remote_branch: main

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - navigation.top
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/apiad
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AlejandroPiad
    - icon: fontawesome/brands/telegram
      link: https://t.me/apiadnet

copyright: CC 4.0 BY-NC-SA &copy; 2022 - Alejandro Piad Morffis

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - User Guide: guide.md
  - Examples:
    - Welcome: examples/index.md
    - Color spaces: examples/color-spaces.md
    - Fluid grid: examples/fluid-grid.md
    - Animations: examples/animations.md
  - API:
    - violetear: api/violetear.__init__.md
    - violetear.stylesheet: api/violetear.stylesheet.md
    - violetear.style: api/violetear.style.md
    - violetear.selector: api/violetear.selector.md
    - violetear.color: api/violetear.color.md
    - violetear.units: api/violetear.units.md
    - violetear.media: api/violetear.media.md
    - violetear.presets: api/violetear.presets.md
    - violetear.helpers: api/violetear.helpers.md
